name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build binaries
    runs-on: windows-2022
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
    steps:
      - name: Wait for previous workflows
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: idk
        run: git config --global url."https://".insteadOf git://

      - name: Check out files
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          # NOTE - If LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Generate project files
        #run: tools/premake5 vs2022 --ci-build
        run: tools/premake5 vs2022

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}} binaries
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=x64 build/h1-mod.sln

      - name: Upload ${{matrix.configuration}} binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}} binaries
          path: |
            build/bin/x64/${{matrix.configuration}}/h1-mod.exe
            build/bin/x64/${{matrix.configuration}}/h1-mod.pdb
            
      - name: Upload ${{matrix.configuration}} data artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}} data artifacts
          path: |
            data/*
  deploy:
    name: Deploy artifacts
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    steps:
      - name: Setup main environment
        if: github.ref == 'refs/heads/main'
        run: echo "H1_MOD_MASTER_PATH=${{ secrets.H1_MOD_MASTER_SSH_PATH }}" >> $GITHUB_ENV

      - name: Setup develop environment
        if: github.ref == 'refs/heads/develop'
        run: echo "H1_MOD_MASTER_PATH=${{ secrets.H1_MOD_MASTER_SSH_PATH_DEV }}" >> $GITHUB_ENV

      - name: Download Release binaries
        uses: actions/download-artifact@v2
        with:
          name: Release binaries
          
      - name: Download Release data artifacts
        uses: actions/download-artifact@v2
        with:
          name: Release data artifacts
          path: data

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.H1_MOD_MASTER_SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.H1_MOD_MASTER_SSH_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Wait for previous workflows
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove old data files
        run: ssh ${{ secrets.H1_MOD_MASTER_SSH_USER }}@${{ secrets.H1_MOD_MASTER_SSH_ADDRESS }} rm -rf ${{ env.H1_MOD_MASTER_PATH }}/h1-mod/data/*

      - name: Upload h1-mod binary
        run: rsync -avz h1-mod.exe ${{ secrets.H1_MOD_MASTER_SSH_USER }}@${{ secrets.H1_MOD_MASTER_SSH_ADDRESS }}:${{ env.H1_MOD_MASTER_PATH }}/h1-mod/

      - name: Upload data files
        run: rsync -avz ./data/ ${{ secrets.H1_MOD_MASTER_SSH_USER }}@${{ secrets.H1_MOD_MASTER_SSH_ADDRESS }}:${{ env.H1_MOD_MASTER_PATH }}/h1-mod/data/

      - name: Publish changes
        run: ssh ${{ secrets.H1_MOD_MASTER_SSH_USER }}@${{ secrets.H1_MOD_MASTER_SSH_ADDRESS }} ${{ secrets.H1_MOD_MASTER_SSH_CHANGE_PUBLISH_COMMAND }}
